### ISSUE TITLE
CDNs not up to date

### ISSUE THREAD

**Issue by flynfish** [adobe-webplatform/balance-text#101] opened 2017-02-10 21:02 UTC
The docs mention 3.0 being available via the cdns, but those links just 404. The latest version on both cdns is v 2.0.0.

**Comment by redmunds** [comment] 2017-02-20 16:30
@flynfish Thanks for reporting bugs! I think the problem is that the library name changed. I'm not quite sure how to get it to update to the new library name without removing all of the libraries for previous releases. Any CDN experts out there who know more about this?

**Comment by rileyjshaw** [comment] 2017-02-21 22:50
@BrianGenisio did you add these?

**Comment by redmunds** [comment] 2017-02-22 00:20
I think I got it figured out. Pending PRs:
* https://github.com/cdnjs/cdnjs/pull/10686
* https://github.com/jsdelivr/jsdelivr/pull/16454

**Comment by redmunds** [comment] 2017-03-13 15:35
@flynfish @rileyjshaw @BrianGenisio Fixed. Closing.

**Closed by redmunds** 2017-03-13 15:35 UTC
