### ISSUE TITLE
forEach used on Nodelist breaks in older browsers

### ISSUE THREAD

**Issue by MattyBalaam** [adobe-webplatform/balance-text#109] opened 2017-07-03 08:38 UTC
In 3.1 there is a function `recursiveCalcNoWrapOffsetsForLine` which tries to use `el.childNodes.forEach`

This throws an error in at the very least Internet Explorer 11 and Edge.

I have reverted to 3.0 for now to fix this issue.

**Comment by redmunds** [comment] 2017-07-16 21:36
@MattyBalaam Thanks for filing bugs. If you know the fix, please submit a pull request :)

**Comment by Rycochet** [comment] 2017-07-17 07:12
The `forEach` method of arrays has been supported since IE9 so the method itself is there. The problem is that `.childNodes` is not actually an array.

Pretty simple fix (stupidly busy elsewhere so not doing a PR) - find the literal "`el.childNodes.forEach(`" and replace with "`[].forEach.call(el.childNodes,`" or  "`Array.prototype.forEach.call(el.childNodes,`" :-)

**Comment by redmunds** [comment] 2017-07-17 15:11
Thanks @Rycochet . FYI, there's already a `forEach` local function to handle this case that I forgot about. Doh!

@MattyBalaam I put up a fix in PR #110 if you have time to test it out. Thanks.

**Comment by redmunds** [comment] 2017-07-18 01:39
Fixed. Closing.

**Closed by redmunds** 2017-07-18 01:39 UTC
